name: "Style check"
description: "Style check using clang-format"

runs:
  using: "composite"
  steps:
    - name: "Run clang-format"
      shell: bash
      run: |
        # We only make check, not changes
        # Use the find command with the variable
        PROJECT_PATH=$(pwd)

        echo $PROJECT_PATH

        # -tr  es usado para reemplazar saltos de linea por espacios
        # Se asigna la lista de archivos (-f) a formatear a la variable SOURCE_FILES con el comando find
        # Se redirige la salida de este comando al archivo $ERROR_FILE_FLAG
        # $SOURCE_FILES contiene la lista de archivos a formatear (se van agregando)
        # https://geekland.eu/uso-del-comando-tr-en-linux-y-unix-con-ejemplos/
        SOURCE_FILES=$(find $PROJECT_PATH/src -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/include -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/lib -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")

        ERROR_FILE_FLAG=$PROJECT_PATH/clang-format_errors.txt

        # clang-format otorga la opcion -i para modificar los archivos directamente
        # Se redirige la salida de este comando al archivo $ERROR_FILE_FLAG (Esto se hace para que el archivo $ERROR_FILE_FLAG contenga la salida del comando)
        # Ademas, se asigna el resultado a la variable CLANG_COMMAND
        # $SOURCE_FILES contiene la lista de archivos a formatear
        # clang provee un "front-end" para los lenguajes en la familia c.
        # https://clang.llvm.org/docs/UsersManual.html
        CLANG_COMMAND=$(clang-format -i $SOURCE_FILES) > ${ERROR_FILE_FLAG}

        echo "Running: clang-format -i $SOURCE_FILES"

        if [ -s $ERROR_FILE_FLAG ]; then
            echo "Error: There are some files that are not formatted correctly"
            exit 1
        else
            echo "All files are formatted correctly. Niiiceee"
            exit 0
        fi

    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Clang-format errors!!!
        path: $PROJECT_PATH/clang-format_errors.txt
        retention-days: 1
