name: "Doc check"
description: "Code documentation generation with Doxygen"

runs:
  using: "composite"
  steps:
    - name: "Run doxygen command"
      shell: bash
      run: |
          # We only make check, not changes
          DOX_CONF_FILE=$(pwd)/Doxyfile

          # Este conjunto de comandos es para configurar el archivo de configuración de Doxygen
          # Proporciona la ruta de los archivos a documentar.
          {
              cat $DOX_CONF_FILE
              echo "INPUT" = $(pwd)/src $(pwd)/include $(pwd)/lib
          } > $DOX_CONF_FILE

          # Generate documentation
          # Ejecuta con privilegios dot -c, que es el comando para generar la documentación (-c indica que se limpie la documentación anterior)
          sudo dot -c

          ERROR_FILE_FLAG=$(pwd)/dox_errors.txt

          # Ejecucion de doxygen -s (sin stdout) para asignar el resultado a la variable DOXYGEN_COMMAND
          # Ademas, redirige la salida de este comando al archivo $ERROR_FILE_FLAG.
          # $DOXYGEN_COMMAND contiene la salida del comando
          # https://www.doxygen.nl/manual/starting.html
          DOXYGEN_COMMAND=$(doxygen -s $DOX_CONF_FILE) > $ERROR_FILE_FLAG

          if [ -s $ERROR_FILE_FLAG ]; then
              echo "Error: There are some files that are not documented correctly"
              exit 1
          else
              echo "All files are documented correctly. Niiiceee"
              exit 0
          fi
    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Doxygen errors!!!
        path: $(pwd)/dox_errors.txt
        retention-days: 1
